function AboutCallBack(~,~,~)

    global miniaturePath aboutIconPath

    M.Aboutfg = figure('Name','About',...
                       'Position',[100, 100, 300, 400],...
                       'NumberTitle','off',...
                       'MenuBar','none',...
                       'Resize','off');

    ax = axes('Parent', M.Aboutfg, 'Position', [0.4, 0.75, 0.2, 0.2]);
    imshow(imread(aboutIconPath), 'Parent', ax);

    uicontrol('Style', 'text',...
                       'Position',[40, 40, 220, 250],...
                       'String', ...
                      {'Synthetic Moonquake Generator',... 
                       'Version: 1.0'},...
                       'HorizontalAlignment','center',...
                       'FontSize',10,...
                       'FontWeight','bold');
                       


    uicontrol('Style', 'text',...
                       'Position',[40, -25, 220, 250],...
                       'String', ...
                      {'Oscar Arcila',...
                       'oscar.arcila@correounivalle.edu.co',...
                       '',...
                       'Daniel Gomez',...
                       'daniel.gomez@correounivalle.edu.co',...
                       '',...
                       'Alejandro Cruz',...
                       'alejandro.cruz@correounivalle.edu.co',...
                       '',...
                       '',...
                       'School of Civil Engineering',...
                       'Universidad del Valle',...
                       'Colombia'},...
                       'HorizontalAlignment','center',...
                       'FontSize',8);
    
    jframe = get(M.Aboutfg,'javaframe');
    jframe.setFigureIcon(javax.swing.ImageIcon(miniaturePath));

    movegui(M.Aboutfg, 'center');
    
end
