M.pn8 = uipanel('Parent',M.tb2,...
                 'Units','normalized',...
                 'Position',[0.025 0.7550 0.25 0.15],...
                 'Title','Response Spectrum Periods');

TN.Tminlabel = uicontrol('Parent',M.pn8,...
                      'Units','normalized',...
                      'FontSize',8,...
                      'HorizontalAlignment','left',...
                      'Style','text',...
                      'Position',[0.075 0.225*2/3+0.600 0.95 1/6],...
                      'String','Minimum Period:');	

TN.Tminedit = uicontrol('Parent',M.pn8,...
                     'style','edit',...
                     'FontSize',8,...
                     'units','normalized',...
                     'position',[0.425 0.225*2/3+0.600 0.20 1/6],...
                     'string',num2str(TN.Tmin,'%.3f'),...
                     'Tooltip','Write Desired Minimun Response Spectrum Period [ s ]',...
                     'callback',{@TNCallBack,'Tmin'});

TN.Tminlabel2 = uicontrol('Parent',M.pn8,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.65 0.225*2/3+0.600 0.95 1/6],...
                       'String','[ s ]');	

TN.Tmaxlabel = uicontrol('Parent',M.pn8,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.075 0.225*2/3+0.300 0.95 1/6],...
                       'String','Maximum Period:');
                       
TN.Tmaxedit = uicontrol('Parent',M.pn8,...
                      'style','edit',...
                      'FontSize',8,...
                      'units','normalized',...
                      'position',[0.425 0.225*2/3+0.300 0.20 1/6],...
                      'string',num2str(TN.Tmax,'%.3f'),...
                      'Tooltip','Write Desired Maximum Response Spectrum Period [ s ]',...
                      'callback',{@TNCallBack,'Tmax'});

TN.Tmaxlabel2 = uicontrol('Parent',M.pn8,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','left',...
                        'Style','text',...
                        'Position',[0.65 0.225*2/3+0.300 0.95 1/6],...
                        'String','[ s ]');	

TN.Tnumlabel = uicontrol('Parent',M.pn8,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.075 0.225*2/3 0.95 1/6],...
                       'String','Number of Periods:');
                       
TN.Tnumedit = uicontrol('Parent',M.pn8,...
                      'style','edit',...
                      'FontSize',8,...
                      'units','normalized',...
                      'position',[0.425 0.225*2/3 0.20 1/6],...
                      'string',num2str(TN.Tnum,'%.0f'),...
                      'Tooltip','Write Desired Response Spectrum Number of Periods [ - ]',...
                      'callback',{@TNCallBack,'Tnum'});

TN.Tnumlabel2 = uicontrol('Parent',M.pn8,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','left',...
                        'Style','text',...
                        'Position',[0.65 0.225*2/3 0.95 1/6],...
                        'String','[ - ]');