M.pn1 = uipanel('Parent',M.tb1,...
                 'Units','normalized',...
                 'Position',[0.025 0.8805 0.25 0.10],...
                 'Title','White Noise');

GP.Tlabel = uicontrol('Parent',M.pn1,...
                      'Units','normalized',...
                      'FontSize',8,...
                      'HorizontalAlignment','left',...
                      'Style','text',...
                      'Position',[0.15 0.675 0.95 0.20],...
                      'String','Event Duration:');	

GP.Tedit = uicontrol('Parent',M.pn1,...
                     'style','edit',...
                     'FontSize',8,...
                     'units','normalized',...
                     'position',[0.425 0.675 0.20 0.25],...
                     'string',num2str(GP.T,'%.2f'),...
                     'Tooltip','Write Desired Event Duration [ min ]',...
                     'callback',{@GPCallBack,'T'});

GP.Tlabel2 = uicontrol('Parent',M.pn1,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.65 0.675 0.95 0.20],...
                       'String','[ min ]');	

GP.fslabel = uicontrol('Parent',M.pn1,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.075 0.225 0.95 0.20],...
                       'String','Sampling Frequency:');
                       
GP.fsedit = uicontrol('Parent',M.pn1,...
                      'style','edit',...
                      'FontSize',8,...
                      'units','normalized',...
                      'position',[0.425 0.225 0.20 0.25],...
                      'string',num2str(GP.fs,'%.2f'),...
                      'Tooltip','Write Desired Record Sampling Frequency [ Hz ]',...
                      'callback',{@GPCallBack,'fs'});

GP.fslabel2 = uicontrol('Parent',M.pn1,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','left',...
                        'Style','text',...
                        'Position',[0.65 0.225 0.95 0.20],...
                        'String','[ Hz ]');