M.pn3 = uipanel('Parent',M.tb1,...
                 'Units','normalized',...
                 'Position',[0.025 0.010 0.25 0.5595], ...
                 'Title','Temporal Envelope');

TP.pn1 =  uipanel('Parent',M.pn3,...
                  'Units','normalized',...
                  'Position',[0.025 0.75 0.95 0.255]);

axes('Parent',TP.pn1,...
     'Units','normalized',...
     'Position',[0 0 1 1]);

image = imread(temporalWindowPath);
[h, w, ~] = size(image);
imgzoompan(gcf, 'ImgWidth', w, 'ImgHeight', h);
imshow(image);

TP.pn2 =  uipanel('Parent',M.pn3,...
                  'Units','normalized',...
                  'Position',[0.025 0.025 0.95 0.70]);

TP.tg = uitabgroup(TP.pn2,'SelectionChangedFcn',@TPtgCallBack);

TP.tb1 = uitab(TP.tg,'Title','Obseved Values');

TP.buttonGroup = uibuttongroup('Parent',TP.tb1,...
                               'Units','normalized',...
                               'FontSize',8,...
                               'Position',[0.025 0.825 0.95 0.17],...
                               'Title', 'Select Desired Moment Magnitude Range');

TP.radioButton1 = uicontrol('Parent',TP.buttonGroup,...
                            'units','normalized',...
                            'Style','radiobutton',...
                            'FontSize',8,...
                            'Position',[0.05, 1/3, 0.90/3, 0.5],...
                            'String', '2.7 to 3.2',...
                            'Callback',@RadioButtonCallBack);
                         
TP.radioButton2 = uicontrol('Parent',TP.buttonGroup,...
                            'units','normalized',...
                            'Style','radiobutton',...
                            'FontSize',8,...
                            'Position',[0.05+0.90/3, 1/3, 0.90/3, 0.5],...
                            'String','3.3 to 3.6',...
                            'Callback',@RadioButtonCallBack);
                         
TP.radioButton3 = uicontrol('Parent',TP.buttonGroup,...
                            'units','normalized',...
                            'Style','radiobutton',...
                            'FontSize',8,...
                            'Position',[0.05+0.90/3*2, 1/3, 0.90/3, 0.5],...
                            'String','3.7 to 4.1',...
                            'Callback',@RadioButtonCallBack);

TP.t1label = uicontrol('Parent',TP.tb1,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','center',...
                       'Style','text',...
                       'Position',[0.025 0.70 0.95 0.1],...
                       'String','Percentage Rise Time t1 [ % ]');

TP.t1Slider = uicontrol('Parent',TP.tb1,...
                        'style','slider',...
                        'units','normalized',...
                        'position',[0.025 0.70-0.05 0.725 0.25*0.10/0.5445/.7],...
                        'min',TP.t1min,...
                        'max',TP.t1max,...
                        'value',TP.t1,...
                        'SliderStep',[0.01 0.01],...
                        'Tooltip','Select Desired Percentage Rise Time t1 [ % ]',...
                        'callback',{@TPCallBack1,'t1'});

TPslid = [0.025 0.70-0.05 0.725 0.045];
TPlbl = [0 TPslid(2)-0.03 0.15 0.03];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(TP.t1min,TP.t1max,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',TP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)),...
              'Tag','t1Slider1ticklabel');
end

TP.t1edit = uicontrol('Parent',TP.tb1,...
                      'style','edit',...
                      'units','normalized',...
                      'position',[0.775 0.70-0.05 0.20 0.25*0.10/0.5445/.7],...
                      'String',num2str(TP.t1,'%.3f'),...
                      'SliderStep',[0.01 0.01],...
                      'Tooltip','Write Desired Percentage Rise Time t1 [ % ]',...
                      'callback',{@TPCallBack2,'t1'});

TP.alabel = uicontrol('Parent',TP.tb1,...
                      'Units','normalized',...
                      'FontSize',8,...
                      'HorizontalAlignment','center',...
                      'Style','text',...
                      'Position',[0.025 0.50 0.95 0.1],...
                      'String','Rise Exponent a [ - ]');

TP.aSlider = uicontrol('Parent',TP.tb1,...
                       'style','slider',...
                       'units','normalized',...
                       'position',[0.025 0.50-0.05 0.725 0.25*0.10/0.5445/.7],...
                       'min',TP.amin,...
                       'max',TP.amax,...
                       'value',TP.a,...
                       'SliderStep',[0.01 0.01],...
                       'Tooltip','Select Desired Rise Exponent a [ - ]',...
                       'callback',{@TPCallBack1,'a'});
             
TPslid = [0.025 0.50-0.05 0.725 0.045];
TPlbl = [0 TPslid(2)-0.03 0.15 0.03];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(TP.amin,TP.amax,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',TP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)),...
              'Tag','aslider1ticklabel');
end
                 
TP.aedit = uicontrol('Parent',TP.tb1,...
                     'style','edit',...
                     'units','normalized',...
                     'position',[0.775 0.50-0.05 0.20 0.25*0.10/0.5445/.7],...
                     'String',num2str(TP.a,'%.3f'),...
                     'SliderStep',[0.01 0.01],...
                     'Tooltip','Write Desired Rise Exponent a [ - ]',...
                     'callback',{@TPCallBack2,'a'});

TP.t2label = uicontrol('Parent',TP.tb1,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','center',...
                       'Style','text',...
                       'Position',[0.025 0.30 0.95 0.1],...
                       'String','Percentage Fall Time t2 [ % ]');

TP.t2Slider = uicontrol('Parent',TP.tb1,...
                        'style','slider',...
                        'units','normalized',...
                        'position',[0.025 0.30-0.05 0.725 0.25*0.10/0.5445/.7],...
                        'min',TP.t2min,...
                        'max',TP.t2max,...
                        'value',TP.t2,...
                        'SliderStep',[0.01 0.01],...
                        'Tooltip','Select Desired Percentage Fall Time t2 [ % ]',...
                        'callback',{@TPCallBack1,'t2'});

TPslid = [0.025 0.30-0.05 0.725 0.045];
TPlbl = [0 TPslid(2)-0.03 0.15 0.03];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(TP.t2min,TP.t2max,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',TP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)),...
              'Tag','t2slider1ticklabel');
end

TP.t2edit = uicontrol('Parent',TP.tb1,...
                      'style','edit',...
                      'units','normalized',...
                      'position',[0.775 0.30-0.05 0.20 0.25*0.10/0.5445/.7],...
                      'string',num2str(TP.t2,'%.3f'),...
                      'SliderStep',[0.01 0.01],...
                      'Tooltip','Write Desired Percentage Fall Time t2 [ % ]',...
                      'callback',{@TPCallBack2,'t2'});

TP.clabel = uicontrol('Parent',TP.tb1,...
                      'Units','normalized',...
                      'FontSize',8,...
                      'HorizontalAlignment','center',...
                      'Style','text',...
                      'Position',[0.025 0.10 0.95 0.1],...
                      'String','Fall Exponent c [ - ]');

TP.cSlider = uicontrol('Parent',TP.tb1,...
                       'style','slider',...
                       'units','normalized',...
                       'position',[0.025 0.10-0.05 0.725 0.25*0.10/0.5445/.7],...
                       'min',TP.cmin,...
                       'max',TP.cmax,...
                       'value',TP.c,...
                       'SliderStep',[0.01 0.01],...
                       'Tooltip','Select Desired Fall Exponent c [ - ]',...
                       'callback',{@TPCallBack1,'c'});

TPslid = [0.025 0.10-0.05 0.725 0.045];
TPlbl = [0 TPslid(2)-0.03 0.15 0.03];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(TP.cmin,TP.cmax,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',TP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)),...
              'Tag','cslider1ticklabel');
end

TP.cedit = uicontrol('Parent',TP.tb1,...
                     'style','edit',...
                     'units','normalized',...
                     'position',[0.775 0.10-0.05 0.20 0.25*0.10/0.5445/.7],...
                     'string',num2str(TP.c,'%.3f'),...
                     'SliderStep',[0.01 0.01],...
                     'Tooltip','Write Desired Fall Exponent c [ - ]',...
                     'callback',{@TPCallBack2,'c'});

TP.tb2 = uitab(TP.tg,'Title','User Values');

TP.t1label2 = uicontrol('Parent',TP.tb2,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.80 0.95 0.1],...
                        'String','Percentage Rise Time t1 [ % ]');
                         
TP.t1edit2 = uicontrol('Parent',TP.tb2,...
                       'style','edit',...
                       'units','normalized',...
                       'position',[0.4 0.80-0.05 0.20 0.25*0.10/0.5445/.7],...
                       'String',num2str(TP.t1,'%.3f'),...
                       'SliderStep',[0.01 0.01],...
                       'Tooltip','Write Desired Percentage Rise Time t1 [ % ]',...
                       'callback',{@TPCallBack3,'t1'});

TP.alabel2 = uicontrol('Parent',TP.tb2,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','center',...
                       'Style','text',...
                       'Position',[0.025 0.60 0.95 0.1],...
                       'String','Rise Exponent a [ - ]');

TP.aedit2 = uicontrol('Parent',TP.tb2,...
                      'style','edit',...
                      'units','normalized',...
                      'position',[0.4 0.60-0.05 0.20 0.25*0.10/0.5445/.7],...
                      'String',num2str(TP.a,'%.3f'),...
                      'SliderStep',[0.01 0.01],...
                      'Tooltip','Write Desired Rise Exponent a [ - ]',...
                      'callback',{@TPCallBack3,'a'});

TP.t2label2 = uicontrol('Parent',TP.tb2,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.40 0.95 0.1],...
                        'String','Percentage Fall Time t2 [ % ]');

TP.t2edit2 = uicontrol('Parent',TP.tb2,...
                       'style','edit',...
                       'units','normalized',...
                       'position',[0.4 0.40-0.05 0.20 0.25*0.10/0.5445/.7],...
                       'string',num2str(TP.t2,'%.3f'),...
                       'SliderStep',[0.01 0.01],...
                       'Tooltip','Write Desired Percentage Fall Time t2 [ % ]',...
                       'callback',{@TPCallBack3,'t2'});

TP.clabel2 = uicontrol('Parent',TP.tb2,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','center',...
                       'Style','text',...
                       'Position',[0.025 0.20 0.95 0.1],...
                       'String','Fall Exponent c [ - ]');

TP.cedit2 = uicontrol('Parent',TP.tb2,...
                      'style','edit',...
                      'units','normalized',...
                      'position',[0.4 0.20-0.05 0.20 0.25*0.10/0.5445/.7],...
                      'string',num2str(TP.c,'%.3f'),...
                      'SliderStep',[0.01 0.01],...
                      'Tooltip','Write Desired Fall Exponent c [ - ]',...
                      'callback',{@TPCallBack3,'c'});
