M.pn2 = uipanel('Parent',M.tb1,...
                'Units','normalized',...
                'Position',[0.025 0.575 0.25 0.30], ...
                'Title','Band-pass Filter');

FP.tg = uitabgroup(M.pn2,'SelectionChangedFcn',@FPtgCallBack);

FP.tb1 = uitab(FP.tg,'Title','Observed Values');

FP.fhlabel1 = uicontrol('Parent',FP.tb1,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.775-0.05 0.95 0.20],...
                        'String','High-pass Cut Frequency [ Hz ]');

FP.fhSlider1 = uicontrol('Parent',FP.tb1,...
                         'style','slider',...
                         'units','normalized',...
                         'position',[0.025 0.80-0.05 0.725 0.25*10/30],...
                         'min',0.2,...
                         'max',0.7,...
                         'value',FP.fhone,...
                         'SliderStep',[0.01 0.01],...
                         'Tooltip','Select Desired High-pass Cut Frequency [ Hz ]',...
                         'callback',{@FPCallBack1,'fh'});

TPslid = [0.025 0.80-0.05 0.725 0.25*10/30];
TPlbl = [0 TPslid(2)-0.10 0.20 0.1];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(0.2,0.7,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',FP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)));
end

FP.fhedit1 = uicontrol('Parent',FP.tb1,...
                       'style','edit',...
                       'units','normalized',...
                       'position',[0.775 0.80-0.05 0.20 0.25*10/30],...
                       'string',num2str(FP.fhone,'%.3f'),...
                       'Tooltip','Write Desired High-pass Cut Frequency [ Hz ]',...
                       'callback',{@FPCallBack2,'fh'});

FP.zhlabel1 = uicontrol('Parent',FP.tb1,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.55-0.05 0.95 0.20],...
                        'String','High-pass Damping [ - ]');

FP.zhSlider1 = uicontrol('Parent',FP.tb1,...
                         'style','slider',...
                         'units','normalized',...
                         'position',[0.025 0.575-0.05 0.725 0.25*10/30],...
                         'min',0.08,...
                         'max',50,...
                         'value',FP.zhone,...
                         'SliderStep',[0.01 0.01],...
                         'Tooltip','Select Desired High-pass Damping [ - ]',...
                         'callback',{@FPCallBack1,'zh'});

TPslid = [0.025 0.575-0.05 0.725 0.25*10/30];
TPlbl = [0 TPslid(2)-0.10 0.20 0.1];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(0.08,50,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',FP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)));
end

FP.zhedit1 = uicontrol('Parent',FP.tb1,...
                       'style','edit',...
                       'units','normalized',...
                       'position',[0.775 0.575-0.05 0.20 0.25*10/30],...
                       'string',num2str(FP.zhone,'%.3f'),...
                       'Tooltip','Write Desired High-pass Damping [ - ]',...
                       'callback',{@FPCallBack2,'zh'});

FP.fgglabel1 = uicontrol('Parent',FP.tb1,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.325-0.05 0.95 0.20],...
                        'String','Low-pass Cut Frequency [ Hz ]');

FP.fggSlider1 = uicontrol('Parent',FP.tb1,...
                          'style','slider',...
                          'units','normalized',...
                          'position',[0.025 0.35-0.05 0.725 0.25*10/30],...
                          'min',0.60,...
                          'max',FP.fggmaxone,...
                          'value',FP.fggone,...
                          'SliderStep',[0.01 0.01],...
                          'Tooltip','Select Desired Low-pass Cut Frequency [ Hz ]',...
                          'callback',{@FPCallBack1,'fgg'});

TPslid = [0.025 0.35-0.05 0.725 0.20];
TPlbl = [0 TPslid(2)-0.10 0.20 0.1];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(0.6,FP.fggmaxone,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',FP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)));
end

FP.fggedit1 = uicontrol('Parent',FP.tb1,...
                        'style','edit',...
                        'units','normalized',...
                        'position',[0.775 0.35-0.05 0.20 0.25*10/30],...
                        'string',num2str(FP.fggone,'%.3f'),...
                        'Tooltip','Write Desired Low-pass Cut Frequency [ Hz ]',...
                        'callback',{@FPCallBack2,'fgg'});

FP.zglabel1 = uicontrol('Parent',FP.tb1,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.10-0.05 0.95 0.20],...
                        'String','Low-pass Damping [ - ]');

FP.zgSlider1 = uicontrol('Parent',FP.tb1,...
                         'style','slider',...
                         'units','normalized',...
                         'position',[0.025 0.125-0.05 0.725 0.25*10/30],...
                         'min',0.019,...
                         'max',0.153,...
                         'value',FP.zgone,...
                         'SliderStep',[0.01 0.01],...
                         'Tooltip','Select Desired Low-pass Damping [ - ]',...
                         'callback',{@FPCallBack1,'zg'});

TPslid = [0.025 0.125-0.05 0.725 0.20];
TPlbl = [0 TPslid(2)-0.10 0.20 0.1];
Tnticks = 5;
Tlblmargin = 0.05;
Tlblvals = linspace(0.019,0.153,Tnticks);
for k = 1:Tnticks
    Txpos = (Tlblmargin + (k-1)*(TPslid(3) - 2*Tlblmargin)/(Tnticks-1)) - TPlbl(3)/2;
    TPlbl(1) = 0.025 + Txpos;
    uicontrol('Parent',FP.tb1,...
              'Units','normalized',...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'Style','text',...
              'Position',TPlbl,...
              'String',sprintf('%.3f',Tlblvals(k)));
end

FP.zgedit1 = uicontrol('Parent',FP.tb1,...
                       'style','edit',...
                       'units','normalized',...
                       'position',[0.775 0.125-0.05 0.20 0.25*10/30],...
                       'string',num2str(FP.zgone,'%.3f'),...
                       'Tooltip','Write Desired Low-pass Damping [ - ]',...
                       'callback',{@FPCallBack2,'zg'});

FP.tb2 = uitab(FP.tg,'Title','User Values');

FP.fholabel2 = uicontrol('Parent',FP.tb2,...
                         'Units','normalized',...
                         'FontSize',8,...
                         'HorizontalAlignment','center',...
                         'Style','text',...
                         'Position',[0.025 0.775-0.05 0.95 0.20],...
                         'String','High-pass Filter Order [ - ]');

FP.fhoedit2 = uicontrol('Parent',FP.tb2,...
                         'style','edit',...
                         'units','normalized',...
                         'position',[0.40 0.80-0.05 0.20 0.25*0.10/0.30],...
                         'string',num2str(FP.fhotwo,'%.0f'),...
                         'Tooltip','Write Desired High-pass Filter Order [ - ]',...
                         'callback',{@FPCallBack3,'fho'});

FP.fhlabel2 = uicontrol('Parent',FP.tb2,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','center',...
                        'Style','text',...
                        'Position',[0.025 0.55-0.05 0.95 0.20],...
                        'String','High-pass Cut Frequency [ Hz ]');

FP.fhedit2 = uicontrol('Parent',FP.tb2,...
                       'style','edit',...
                       'units','normalized',...
                       'position',[0.40 0.575-0.05 0.20 0.25*0.10/0.30],...
                       'string',num2str(FP.fhtwo,'%.3f'),...
                       'Tooltip','Write Desired High-pass Cut Frequency',...
                       'callback',{@FPCallBack3,'fh'});

FP.fggolabel2 = uicontrol('Parent',FP.tb2,...
                          'Units','normalized',...
                          'FontSize',8,...
                          'HorizontalAlignment','center',...
                          'Style','text',...
                          'Position',[0.025 0.325-0.05 0.95 0.20],...
                          'String','Low-pass Filter Order [ - ] ');

FP.fggoedit2 = uicontrol('Parent',FP.tb2,...
                         'style','edit',...
                         'units','normalized',...
                         'position',[0.40 0.35-0.05 0.20 0.25*0.10/0.30],...
                         'string',num2str(FP.fggotwo,'%.0f'),...
                         'Tooltip','Write Desired Low-pass Filter Order',...
                         'callback',{@FPCallBack3,'fggo'});

FP.fgglabel2 = uicontrol('Parent',FP.tb2,...
                         'Units','normalized',...
                         'FontSize',8,...
                         'HorizontalAlignment','center',...
                         'Style','text',...
                         'Position',[0.025 0.10-0.05 0.95 0.20],...
                         'String','Low-pass Cut Frequency [ Hz ]');

FP.fggedit2 = uicontrol('Parent',FP.tb2,...
                        'style','edit',...
                        'units','normalized',...
                        'position',[0.40 0.125-0.05 0.20 0.25*0.10/0.30],...
                        'string',num2str(FP.fggtwo,'%.3f'),...
                        'Tooltip','Write Desired Low-pass Cut Frequency',...
                        'callback',{@FPCallBack3,'fgg'});