M.pn6 = uipanel('Parent',M.tb2,...
                 'Units','normalized',...
                 'Position',[0.025 0.9105 0.250 0.070],...
                 'Title','Damping Ratio');

ZZ.Zlabel = uicontrol('Parent',M.pn6,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.075 0.225*10/7 0.950 0.25*10/7],...
                       'String','Damping Ratio:');
                       
ZZ.Zedit = uicontrol('Parent',M.pn6,...
                      'style','edit',...
                      'FontSize',8,...
                      'units','normalized',...
                      'position',[0.425 0.225*10/7 0.200 1.10*0.25*10/7],...
                      'string',num2str(ZZ.Z,'%.3f'),...
                      'Tooltip','Write Desired Damping Ratio [ - ]',...
                      'callback',{@ZZCallBack,'Z'});

ZZ.Zlabel2 = uicontrol('Parent',M.pn6,...
                        'Units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','left',...
                        'Style','text',...
                        'Position',[0.650 0.225*10/7 0.950 0.25*10/7],...
                        'String','[ % ]');