uicontrol('Parent',M.tb2,...
          'units','normalized',...
          'pos',[0.875 0.025 0.100 .050],...
          'FontSize',8,...
          'HorizontalAlignment','center',...
          'Style','Push',...
          'String','Export Spectra', ...
          'callback',@ExportSpecCallBack);