M.pn4 = uipanel('Parent',M.tb1,...
                'Units','normalized',...
                'Position',[0.30 0.010 0.20 0.065],...
                'Title','Peak Ground Acceleration');

TP.PGAlabel = uicontrol('Parent',M.pn4,...
                        'units','normalized',...
                        'FontSize',8,...
                        'HorizontalAlignment','left',...
                        'Style','text',...
                        'Position',[0.10, 0.20, 0.40, 0.5],...
                        'String','Record PGA:');

TP.PGAedit = uicontrol('Parent',M.pn4,...
                       'units','normalized',...
                       'Style','edit',...
                       'String',num2str(TP.PGA,'%.3f'),...
                       'Position', [0.40, 0.25, 0.20, 0.5],...
                       'Tooltip','Write Desired Record PGA [ m/s/s ]',...
                       'Callback', @PGACallBack);

TP.PGAlabel2 = uicontrol('Parent',M.pn4,...
                         'units','normalized',...
                         'FontSize',8,...
                         'HorizontalAlignment','left',...
                         'Style','text',...
                         'Position',[0.65, 0.20, 0.20, 0.5],...
                         'String','[ m/s/s ]');