M.pn9 = uipanel('Parent',M.tb2,...
                 'Units','normalized',...
                 'Position',[0.025 0.6795 0.250 0.070],...
                 'Title','Gravitational Acceleration Magnitude');

GG.gglabel = uicontrol('Parent',M.pn9,...
                      'Units','normalized',...
                      'FontSize',8,...
                      'HorizontalAlignment','left',...
                      'Style','text',...
                      'Position',[0.075 0.225*10/7 0.950 0.25*10/7],...
                      'String','Gravitational Acc.:');	

GG.ggedit = uicontrol('Parent',M.pn9,...
                     'style','edit',...
                     'FontSize',8,...
                     'units','normalized',...
                     'position',[0.425 0.225*10/7 0.200 1.10*0.25*10/7],...
                     'string',num2str(GG.gg,'%.3f'),...
                     'Tooltip','Write Desired Gravitational Acceleration [ m/s/s ]',...
                     'callback',{@GGCallBack,'gg'});

GG.gglabel2 = uicontrol('Parent',M.pn9,...
                       'Units','normalized',...
                       'FontSize',8,...
                       'HorizontalAlignment','left',...
                       'Style','text',...
                       'Position',[0.650 0.225*10/7 0.950 0.25*10/7],...
                       'String','[ m/s/s ]');